[tool.black]
skip-string-normalization = true

[tool.flake8]
show-source = true
max-line-length = 99
ignore = [
  "E501",  # line too long (80 chars)
  "W503",  # line break before binary operator
]

[tool.isort]
profile = "black"
py_version = 39
