services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  ari_amqp:
    image: asterisk_amqp
    ports:
      - "5039"
    volumes:
      - "./etc/asterisk:/etc/asterisk"
    command: "asterisk -fTvvv"

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
    volumes:
      - type: tmpfs
        target: "/var/lib/rabbitmq"
