services:
  sync:
    depends_on:
      - ari_amqp
      - rabbitmq
    environment:
      TARGETS: "ari_amqp:5039 rabbitmq:5672"

  ari_amqp:
    volumes:
      - "./etc/asterisk/stasis_amqp.headers.conf:/etc/asterisk/stasis_amqp.conf"
